config/routes.rb
MailAdmin::Application.routes.draw do
  devise_for :managers, path_names: {
    sign_in: 'login', sign_out: 'logout'
  }
# :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  resources :users do
    post :block, on: :member
  end

  resources :domains do
    post :block, on: :member
  end

  resource :profile

  root :to => 'site#index'
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  default_scope order(:name)

  has_many :users

  validates :name, presence: true, uniqueness: true
  validate :domain_name

  def to_s
    name
  end

  protected

  def domain_name
    begin
      domain = Whois.whois(name)
      if domain.available?
        errors.add(:name, 'domain name not registered')
      end
    rescue Whois::ServerNotFound => e
      errors.add(:name, 'invalid domain name')
    end
  end
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :trackable, :validatable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :set_gid_uid
  before_save :hash_password, if: lambda { |a| a.password_changed? }

  default_scope order(:name)

  belongs_to :domain

  validates :uid, :gid, numericality: true
  validates :username, uniqueness: { scope: :domain_id }
  validates :username, :name, :uid, :gid, :domain_id, presence: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password, confirmation: true, length: { minimum: 6 },
    unless: lambda { |a| a.password.blank? }

  attr_accessor :password_confirmation

  protected

  def set_gid_uid
    self.uid = Rails.configuration.mail.uid.to_i
    self.gid = Rails.configuration.mail.gid.to_i
  end

  def hash_password
    salt = SecureRandom.hex
    hash = Base64.encode64(Digest::SHA256.digest(password + salt) + salt)
    self.password = '{SSHA256}%s' % hash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_manager!
  protect_from_forgery
  layout :select_layout

  protected

  def select_layout
    if devise_controller?
      'site'
    else
      'backoffice'
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    new_manager_session_path
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || url_for(:users)
  end
end

app/controllers/concerns/blockable.rb
module Blockable
  extend ActiveSupport::Concern

  def block
    resource = controller_name.classify.constantize.find(params[:id])

    resource.toggle!(:active)
    respond_with(resource, location: controller_name.to_sym)
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  include Blockable

  respond_to :html
  def index
    @domains = Domain.all
    respond_with(@domains)
  end

  def new
    @domain = Domain.new
    respond_with(@domain)
  end

  def edit
    @domain = Domain.find(params[:id])

    respond_with(@domain)
  end

  def create
    @domain = Domain.new(params[:domain])

    if @domain.save
      flash[:success] = 'Domain successfully saved!'
    else
      flash[:error] = 'There was an error while saving the domain!'
    end

    respond_with(@domain, :location => :domains)
  end

  def update
    @domain = Domain.find(params[:id])

    if @domain.update_attributes(params[:domain])
      flash[:success] = 'Domain successfully saved!'
    else
      flash[:error] = 'There was an error while trying to save the domain!'
    end

    respond_with(@domain, location: :domains)
  end

  def destroy
    @domain = Domain.find(params[:id])

    @domain.destroy

    respond_with(@domain)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @manager = current_manager
  end

  def update
    @manager = current_manager

    result ||= @manager.update_attributes(params[:manager]) if params.key?(:manager)
    result ||= @manager.update_with_password(params[:password]) if params.key?(:password)

    if result
      sign_in(@manager, :bypass => true)
      redirect_to :users, notice: 'Profile successfully updated!'
    else
      render :show
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ActionController::Base
  layout 'site'

  def index
    redirect_to new_manager_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Blockable

  respond_to :html

  def index
    @users = User.all

    respond_with(@users)
  end

  def new
    @user = User.new

    respond_with(@user)
  end

  def edit
    @user = User.find(params[:id])

    respond_with(@user)
  end

  def create
    @user = User.new(params[:user])
    
    if @user.save
      flash[:success] = 'User successfully saved!'
    else
      flash[:error] = 'There was an error while saving the users!'
    end

    respond_with(@user, location: :users)
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      flash[:success] = 'User successfully updated!'
    else
      flash[:error] = 'There was an error while updating the user!'
    end

    respond_with(@user, location: :users)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_with(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def toggle_action(status)
    (status) ? 'Disable' : 'Enable'
  end

  def status(state)
    result = (state) ? 'Active' : 'Inactive'

    content_tag(:span, result, class: "#{result.downcase} label")
  end
end

app/views/domains/_form.html.haml
= simple_form_for(@domain) do |f|
  %fieldset
    %ul.form
      = f.input :name
      %li.actions
        = f.button :submit, class: 'small radius'

app/views/domains/edit.html.haml
- content_for(:titlebar) do
  %h2 Edit E-Mail Domain 
  .item-actions
    = link_to('Cancel', :domains, class: 'small white radius button')

= render 'form'

app/views/domains/index.html.haml
- content_for(:titlebar) do
  %h2 E-Mail Domains
  .item-actions
    %a.small.blue.button.radius{ :href => url_for([:new, :domain])} Add
    %a.small.red.button.radius{ :href => '#'} Delete

%table.zebra.bordered
  %thead
    %tr
      %th.checkbox= check_box_tag('teste')
      %th Domain
      %th Status
      %th.actions Actions
  - if @domains.any?
    %tbody
      - @domains.each do |domain|
        %tr
          %td.checkbox= check_box_tag('teste')
          %td= link_to(domain.name, [:edit, domain])
          %td= status(domain.active)
          %td
            = link_to('Edit', [:edit, domain])
            |
            = link_to(toggle_action(domain.active), [:block, domain], method: :post)
            |
            = link_to('Delete', domain, method: :delete)

app/views/domains/new.html.haml
- content_for(:titlebar) do
  %h2 New E-Mail Domain 
  .item-actions
    = link_to('Cancel', :domains, class: 'small white radius button')

= render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :charset => 'utf-8' }
    %title MailAdmin
    = stylesheet_link_tag('application', :media => 'all')
    = javascript_include_tag('application')
    = csrf_meta_tags

  %body
    %header
      = link_to(image_tag('branding/logo.png'))
      #userbox
        %ul
          %li= link_to('Dashboard', "#")
          %li= link_to('ravage@fragmentized.net', '#')
          %li= link_to('Logout', '#')
    .nav-background
    #page
      %nav
        %h3 E-Mail
        %ul
          %li
            = link_to('Virtual Users', :users, class: ('active' if controller_name == 'users'))
          %li
            = link_to('Domain', :domains, class: ('active' if controller_name == 'domains'))
      %article
        = yield

app/views/layouts/backoffice.html.haml
!!!
%html
  %head
    %meta{ :charset => 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    %title MailAdmin
    = stylesheet_link_tag('backoffice', :media => 'all')
    = javascript_include_tag('application')
    = csrf_meta_tags

  %body
    %header
      = link_to(image_tag('branding/logo.png'), 'http://mk-is.pt/')
      - if manager_signed_in?
        #userbox
          %ul
            %li= link_to('Dashboard', :users)
            %li= link_to(current_manager.email, :profile)
            %li= link_to('Logout', destroy_manager_session_path, method: 'delete')
    .nav-background
    #page
      %nav
        %h3 E-Mail
        %ul
          %li
            = link_to('Virtual Users', :users, class: ('active' if controller_name == 'users'))
          %li
            = link_to('Domain', :domains, class: ('active' if controller_name == 'domains'))
      %article
        .titlebar.clearfix
          = yield :titlebar
        - flash.each do |key, msg|
          .alert-box{ class: key }= msg
        = yield

app/views/layouts/site.html.haml
!!!
%html
  %head
    %meta{ :charset => 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    %title MailAdmin
    = stylesheet_link_tag('site', :media => 'all')
    = javascript_include_tag('application')
    = csrf_meta_tags

  %body
    %header
      = link_to(image_tag('branding/logo.png'), 'http://mk-is.pt/')
      - if manager_signed_in?
        #userbox
          %ul
            %li= link_to('Dashboard', :users)
            %li= link_to(current_manager.email, :profile)
            %li= link_to('Logout', destroy_manager_session_path, method: 'delete')
    - flash.each do |key, msg|
      .alert-box{ class: key }= msg
    #page
      %article
        = yield

app/views/profiles/show.html.haml
- content_for(:titlebar) do
  %h2 Account Settings

= simple_form_for(@manager, url: :profile, method: :put) do |f|
  %fieldset
    %ul.form
      = f.input :email
      %li.actions
        = f.button :submit, class: 'small button radius'
      
= simple_form_for(@manager, as: :password, url: :profile, method: :put) do |f|
  %fieldset
    %ul.form
      = f.input :current_password, hint: '(old password)'
      = f.input :password, hint: '(new password)'
      = f.input :password_confirmation, hint: '(new password confirmation)'
      %li.actions
        = f.button :submit, 'Update Password', class: 'small radius'

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  %fieldset
    %ul.form
      = f.input :name
      = f.input :username, wrapper_html: { class: 'inline' } do
        = f.text_field :username
        @
        = f.collection_select :domain_id, Domain.all, :id, :name
      = f.input :home
      = f.input :password
      = f.input :password_confirmation
      %li.actions
        = f.button :submit, class: 'small radius'

app/views/users/edit.html.haml
- content_for(:titlebar) do
  %h2 Edit Virtual User
  .item-actions
    = link_to('Cancel', :users, class: 'small white radius button')

= render 'form'

app/views/users/index.html.haml
- content_for(:titlebar) do
  %h2 Virtual Users
  .item-actions
    %a.small.blue.button.radius{ :href => url_for([:new, :user])} Add
    %a.small.red.button.radius{ :href => '#'} Delete

%table.zebra.bordered
  %thead
    %tr
      %th.checkbox= check_box_tag('teste')
      %th Name
      %th Username
      %th Domain
      %th Status
      %th.actions Actions
  - if @users.any?
    %tbody
      - @users.each do |user|
        %tr
          %td.checkbox= check_box_tag('teste')
          %td= link_to(user.name, [:edit, user])
          %td= user.username
          %td= link_to(user.domain, [:edit, user.domain])
          %td= status(user.active)
          %td
            = link_to('Edit', [:edit, user])
            |
            = link_to(toggle_action(user.active), [:block, user], method: :post)
            |
            = link_to('Delete', user, method: :delete)

app/views/users/new.html.haml
- content_for(:titlebar) do
  %h2 New Virtual User
  .item-actions
    = link_to('Cancel', :users, class: 'small white radius button')

= render 'form'